package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"time"

	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	db "github.com/starjardin/onja-products/db/sqlc"
	"github.com/starjardin/onja-products/graph/model"
	"github.com/starjardin/onja-products/services"
	"github.com/starjardin/onja-products/utils"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInput) (*model.SignupResponse, error) {
	// Use the UserService for user creation with validation
	result, err := r.UserService.CreateUser(ctx, services.CreateUserParams{
		Username:      input.Username,
		Password:      input.Password,
		Email:         input.Email,
		FullName:      input.FullName,
		Address:       input.Address,
		PhoneNumber:   input.PhoneNumber,
		PaymentMethod: input.PaymentMethod,
		CompanyID:     input.CompanyID,
	})
	if err != nil {
		return nil, err
	}

	return &model.SignupResponse{
		User: &model.User{
			ID:            fmt.Sprintf("%d", result.User.ID),
			Username:      result.User.Username,
			Email:         result.User.Email,
			FullName:      result.User.FullName,
			Address:       result.User.Address.String,
			PhoneNumber:   result.User.PhoneNumber.String,
			PaymentMethod: result.User.PaymentMethod.String,
		},
		Message: result.Message,
	}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (*model.AuthResponse, error) {
	result, err := r.UserService.VerifyEmail(ctx, token)
	if err != nil {
		return nil, err
	}

	return &model.AuthResponse{
		User: &model.User{
			ID:            fmt.Sprintf("%d", result.User.ID),
			Username:      result.User.Username,
			Email:         result.User.Email,
			FullName:      result.User.FullName,
			Address:       result.User.Address.String,
			PhoneNumber:   result.User.PhoneNumber.String,
			PaymentMethod: result.User.PaymentMethod.String,
		},
		Token:        result.AccessToken,
		RefreshToken: result.RefreshToken,
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	userID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	params := db.UpdateUserParams{
		ID: int32(userID),
	}

	if input.Password != nil {
		hashedPassword, err := utils.HashedPassword(*input.Password)
		if err != nil {
			return nil, fmt.Errorf("failed to hash password: %w", err)
		}
		params.HashedPassword = pgtype.Text{Valid: true, String: hashedPassword}
		params.PasswordChangedAt = pgtype.Timestamptz{Time: time.Now(), Valid: true}
	}

	if input.Username != nil {
		params.Username = pgtype.Text{Valid: true, String: *input.Username}
	}

	if input.Email != nil {
		params.Email = pgtype.Text{Valid: true, String: *input.Email}
	}

	if input.FullName != nil {
		params.FullName = pgtype.Text{Valid: true, String: *input.FullName}
	}

	if input.Address != nil {
		params.Address = pgtype.Text{Valid: true, String: *input.Address}
	}

	if input.PhoneNumber != nil {
		params.PhoneNumber = pgtype.Text{Valid: true, String: *input.PhoneNumber}
	}

	if input.PaymentMethod != nil {
		params.PaymentMethod = pgtype.Text{Valid: true, String: *input.PaymentMethod}
	}

	if input.CompanyID != nil {
		params.CompanyID = pgtype.Int4{Valid: true, Int32: int32(*input.CompanyID)}
	} else {
		params.CompanyID = pgtype.Int4{Valid: false}
	}

	user, err := r.Store.UpdateUser(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	return &model.User{
		ID:            fmt.Sprintf("%d", user.ID),
		Username:      user.Username,
		Email:         user.Email,
		FullName:      user.FullName,
		Address:       user.Address.String,
		PhoneNumber:   user.PhoneNumber.String,
		PaymentMethod: user.PaymentMethod.String,
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	userID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid user ID: %w", err)
	}

	err = r.Store.DeleteUser(ctx, int32(userID))
	if err != nil {
		return false, fmt.Errorf("failed to delete user: %w", err)
	}

	return true, nil
}

// CreateCompany is the resolver for the createCompany field.
func (r *mutationResolver) CreateCompany(ctx context.Context, name string) (*model.Company, error) {
	company, err := r.Store.CreateCompany(ctx, name)
	if err != nil {
		return nil, fmt.Errorf("failed to create company: %w", err)
	}

	return &model.Company{
		ID:   fmt.Sprintf("%d", company.ID),
		Name: company.Name,
	}, nil
}

// UpdateCompany is the resolver for the updateCompany field.
func (r *mutationResolver) UpdateCompany(ctx context.Context, id string, name string) (*model.Company, error) {
	companyID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid company ID: %w", err)
	}

	company, err := r.Store.UpdateCompany(ctx, db.UpdateCompanyParams{
		ID:   int32(companyID),
		Name: name,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update company: %w", err)
	}

	return &model.Company{
		ID:   fmt.Sprintf("%d", company.ID),
		Name: company.Name,
	}, nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	authCtx, err := GetAuthFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required")
	}

	ownerID := int32(authCtx.UserID)

	product, err := r.ProductService.CreateProduct(ctx, services.CreateProductParams{
		Name:            input.Name,
		Description:     input.Description,
		Price:           input.Price,
		OwnerID:         ownerID,
		CompanyID:       input.CompanyID,
		ImageLink:       input.ImageLink,
		AvailableStocks: input.AvailableStocks,
		IsNegotiable:    input.IsNegotiable,
		Category:        input.Category,
	})
	if err != nil {
		return nil, err
	}

	var responseCompanyID int
	if product.CompanyID.Valid {
		responseCompanyID = int(product.CompanyID.Int32)
	} else {
		responseCompanyID = 0
	}

	return &model.Product{
		ID:              fmt.Sprintf("%d", product.ID),
		Name:            product.Name,
		Description:     product.Description,
		Price:           int(product.Price),
		OwnerID:         int(product.OwnerID),
		CompanyID:       &responseCompanyID,
		ImageLink:       product.ImageLink,
		AvailableStocks: int(product.AvailableStocks),
		IsNegotiable:    product.IsNegotiable,
		Category:        product.Category,
	}, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	productID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID: %w", err)
	}

	params := db.UpdateProductParams{
		ID: int32(productID),
	}

	if input.ImageLink != nil {
		params.ImageLink = pgtype.Text{Valid: true, String: *input.ImageLink}
	}

	if input.Description != nil {
		params.Description = pgtype.Text{Valid: true, String: *input.Description}
	}

	if input.AvailableStocks != nil {
		params.AvailableStocks = pgtype.Int4{Valid: true, Int32: int32(*input.AvailableStocks)}
	}

	if input.IsNegotiable != nil {
		params.IsNegotiable = pgtype.Bool{Valid: true, Bool: *input.IsNegotiable}
	}

	if input.Sold != nil {
		params.Sold = pgtype.Bool{Valid: true, Bool: *input.Sold}
	}

	if input.Price != nil {
		params.Price = pgtype.Int4{Valid: true, Int32: int32(*input.Price)}
	}

	if input.Category != nil {
		params.Category = pgtype.Text{Valid: true, String: *input.Category}
	}

	product, err := r.Store.UpdateProduct(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to update product: %w", err)
	}

	var responseCompanyID int
	if product.CompanyID.Valid {
		responseCompanyID = int(product.CompanyID.Int32)
	}

	return &model.Product{
		ID:              fmt.Sprintf("%d", product.ID),
		Name:            product.Name,
		Description:     product.Description,
		Price:           int(product.Price),
		OwnerID:         int(product.OwnerID),
		CompanyID:       &responseCompanyID,
		ImageLink:       product.ImageLink,
		AvailableStocks: int(product.AvailableStocks),
		IsNegotiable:    product.IsNegotiable,
		Sold:            product.Sold,
		Likes:           int(product.Likes),
		Category:        product.Category,
	}, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	authCtx, err := GetAuthFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required")
	}

	_, err = r.ProductService.DeleteProduct(ctx, id, int32(authCtx.UserID))
	if err != nil {
		return false, err
	}

	return true, nil
}

// DeleteCompany is the resolver for the deleteCompany field.
func (r *mutationResolver) DeleteCompany(ctx context.Context, id string) (bool, error) {
	companyID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid company ID: %w", err)
	}

	err = r.Store.DeleteCompany(ctx, int32(companyID))
	if err != nil {
		return false, fmt.Errorf("failed to delete company: %w", err)
	}

	return true, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthResponse, error) {
	result, err := r.UserService.Login(ctx, services.LoginParams{
		Email:    email,
		Password: password,
	})
	if err != nil {
		return nil, err
	}

	return &model.AuthResponse{
		User: &model.User{
			ID:            fmt.Sprintf("%d", result.User.ID),
			Username:      result.User.Username,
			Email:         result.User.Email,
			FullName:      result.User.FullName,
			Address:       result.User.Address.String,
			PhoneNumber:   result.User.PhoneNumber.String,
			PaymentMethod: result.User.PaymentMethod.String,
		},
		Token:        result.AccessToken,
		RefreshToken: result.RefreshToken,
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.AuthResponse, error) {
	payload, err := r.TokenMaker.VerifyToken(token)
	if err != nil {
		return nil, fmt.Errorf("invalid refresh token: %w", err)
	}

	user, err := r.Store.GetUserByEmail(ctx, payload.Username)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("user not found")
		}
		return nil, fmt.Errorf("failed to find user: %w", err)
	}

	newAccessToken, _, err := r.TokenMaker.CreateToken(user.Username, "user", 24*time.Hour)
	if err != nil {
		return nil, fmt.Errorf("failed to create new access token: %w", err)
	}

	newRefreshToken, _, err := r.TokenMaker.CreateToken(user.Username, "user", 7*24*time.Hour)
	if err != nil {
		return nil, fmt.Errorf("failed to create new refresh token: %w", err)
	}

	return &model.AuthResponse{
		User: &model.User{
			ID:            fmt.Sprintf("%d", user.ID),
			Username:      user.Username,
			Email:         user.Email,
			FullName:      user.FullName,
			Address:       user.Address.String,
			PhoneNumber:   user.PhoneNumber.String,
			PaymentMethod: user.PaymentMethod.String,
		},
		Token:        newAccessToken,
		RefreshToken: newRefreshToken,
	}, nil
}

// AddToCart is the resolver for the addToCart field.
func (r *mutationResolver) AddToCart(ctx context.Context, productID string, quantity int) (*model.CartItem, error) {
	authCtx, err := GetAuthFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required")
	}

	prodID, err := strconv.ParseInt(productID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID: %w", err)
	}

	// Verify product exists
	product, err := r.Store.GetProduct(ctx, int32(prodID))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("product not found")
		}
		return nil, fmt.Errorf("failed to get product: %w", err)
	}

	cartItem, err := r.Store.AddToCart(ctx, db.AddToCartParams{
		UserID:    int32(authCtx.UserID),
		ProductID: int32(prodID),
		Quantity:  int32(quantity),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to add to cart: %w", err)
	}

	var responseCompanyID int
	if product.CompanyID.Valid {
		responseCompanyID = int(product.CompanyID.Int32)
	}

	return &model.CartItem{
		ID:        fmt.Sprintf("%d", cartItem.ID),
		UserID:    int(cartItem.UserID),
		ProductID: int(cartItem.ProductID),
		Quantity:  int(cartItem.Quantity),
		Product: &model.Product{
			ID:              fmt.Sprintf("%d", product.ID),
			Name:            product.Name,
			Description:     product.Description,
			Price:           int(product.Price),
			ImageLink:       product.ImageLink,
			AvailableStocks: int(product.AvailableStocks),
			IsNegotiable:    product.IsNegotiable,
			OwnerID:         int(product.OwnerID),
			CompanyID:       &responseCompanyID,
			Sold:            product.Sold,
			Likes:           int(product.Likes),
			Category:        product.Category,
		},
	}, nil
}

// UpdateCartItemQuantity is the resolver for the updateCartItemQuantity field.
func (r *mutationResolver) UpdateCartItemQuantity(ctx context.Context, productID string, quantity int) (*model.CartItem, error) {
	authCtx, err := GetAuthFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required")
	}

	prodID, err := strconv.ParseInt(productID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID: %w", err)
	}

	// If quantity is 0 or less, remove the item
	if quantity <= 0 {
		err = r.Store.RemoveFromCart(ctx, db.RemoveFromCartParams{
			UserID:    int32(authCtx.UserID),
			ProductID: int32(prodID),
		})
		if err != nil {
			return nil, fmt.Errorf("failed to remove from cart: %w", err)
		}
		return nil, nil
	}

	cartItem, err := r.Store.UpdateCartItemQuantity(ctx, db.UpdateCartItemQuantityParams{
		UserID:    int32(authCtx.UserID),
		ProductID: int32(prodID),
		Quantity:  int32(quantity),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update cart item: %w", err)
	}

	product, err := r.Store.GetProduct(ctx, int32(prodID))
	if err != nil {
		return nil, fmt.Errorf("product not found: %w", err)
	}

	var responseCompanyID int
	if product.CompanyID.Valid {
		responseCompanyID = int(product.CompanyID.Int32)
	}

	return &model.CartItem{
		ID:        fmt.Sprintf("%d", cartItem.ID),
		UserID:    int(cartItem.UserID),
		ProductID: int(cartItem.ProductID),
		Quantity:  int(cartItem.Quantity),
		Product: &model.Product{
			ID:              fmt.Sprintf("%d", product.ID),
			Name:            product.Name,
			Description:     product.Description,
			Price:           int(product.Price),
			ImageLink:       product.ImageLink,
			AvailableStocks: int(product.AvailableStocks),
			IsNegotiable:    product.IsNegotiable,
			OwnerID:         int(product.OwnerID),
			CompanyID:       &responseCompanyID,
			Sold:            product.Sold,
			Likes:           int(product.Likes),
			Category:        product.Category,
		},
	}, nil
}

// RemoveFromCart is the resolver for the removeFromCart field.
func (r *mutationResolver) RemoveFromCart(ctx context.Context, productID string) (bool, error) {
	authCtx, err := GetAuthFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required")
	}

	prodID, err := strconv.ParseInt(productID, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid product ID: %w", err)
	}

	err = r.Store.RemoveFromCart(ctx, db.RemoveFromCartParams{
		UserID:    int32(authCtx.UserID),
		ProductID: int32(prodID),
	})
	if err != nil {
		return false, fmt.Errorf("failed to remove from cart: %w", err)
	}

	return true, nil
}

// ClearCart is the resolver for the clearCart field.
func (r *mutationResolver) ClearCart(ctx context.Context) (bool, error) {
	authCtx, err := GetAuthFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required")
	}

	err = r.Store.ClearCart(ctx, int32(authCtx.UserID))
	if err != nil {
		return false, fmt.Errorf("failed to clear cart: %w", err)
	}

	return true, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	userID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	user, err := r.Store.GetUser(ctx, int32(userID))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("user not found")
		}
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	return &model.User{
		ID:            fmt.Sprintf("%d", user.ID),
		Username:      user.Username,
		Email:         user.Email,
		FullName:      user.FullName,
		Address:       user.Address.String,
		PhoneNumber:   user.PhoneNumber.String,
		PaymentMethod: user.PaymentMethod.String,
	}, nil
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context) ([]*model.User, error) {
	users, err := r.Store.GetUsers(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get users: %w", err)
	}

	var result []*model.User
	for _, user := range users {
		result = append(result, &model.User{
			ID:            fmt.Sprintf("%d", user.ID),
			Username:      user.Username,
			Email:         user.Email,
			FullName:      user.FullName,
			Address:       user.Address.String,
			PhoneNumber:   user.PhoneNumber.String,
			PaymentMethod: user.PaymentMethod.String,
		})
	}

	return result, nil
}

// GetCompanies is the resolver for the getCompanies field.
func (r *queryResolver) GetCompanies(ctx context.Context) ([]*model.Company, error) {
	companies, err := r.Store.GetCompanies(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get companies: %w", err)
	}

	var result []*model.Company
	for _, company := range companies {
		result = append(result, &model.Company{
			ID:   fmt.Sprintf("%d", company.ID),
			Name: company.Name,
		})
	}

	return result, nil
}

// GetCompany is the resolver for the getCompany field.
func (r *queryResolver) GetCompany(ctx context.Context, id string) (*model.Company, error) {
	companyID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid company ID: %w", err)
	}

	company, err := r.Store.GetCompany(ctx, int32(companyID))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("company not found")
		}
		return nil, fmt.Errorf("failed to get company: %w", err)
	}

	return &model.Company{
		ID:   fmt.Sprintf("%d", company.ID),
		Name: company.Name,
	}, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	categories, err := r.Store.GetCategories(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get categories: %w", err)
	}

	var result []*model.Category
	for _, category := range categories {
		result = append(result, &model.Category{
			ID:    fmt.Sprintf("%d", category.ID),
			Name:  category.Name,
			Value: category.Value,
		})
	}

	return result, nil
}

// GetProducts is the resolver for the getProducts field.
func (r *queryResolver) GetProducts(ctx context.Context, category *string, sold *bool, isNegotiable *bool, search *string) ([]*model.Product, error) {
	var categoryParam pgtype.Text
	if category != nil && *category != "" {
		categoryParam = pgtype.Text{String: *category, Valid: true}
	} else {
		categoryParam = pgtype.Text{Valid: false}
	}

	var soldParam pgtype.Bool
	if sold != nil {
		soldParam = pgtype.Bool{Bool: *sold, Valid: true}
	} else {
		soldParam = pgtype.Bool{Valid: false}
	}

	var isNegotiableParam pgtype.Bool
	if isNegotiable != nil {
		isNegotiableParam = pgtype.Bool{Bool: *isNegotiable, Valid: true}
	} else {
		isNegotiableParam = pgtype.Bool{Valid: false}
	}

	var searchParam pgtype.Text
	if search != nil && *search != "" {
		searchParam = pgtype.Text{String: *search, Valid: true}
	} else {
		searchParam = pgtype.Text{Valid: false}
	}

	products, err := r.Store.GetProducts(ctx, db.GetProductsParams{
		Category:     categoryParam,
		Sold:         soldParam,
		IsNegotiable: isNegotiableParam,
		Search:       searchParam,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get products: %w", err)
	}

	var result []*model.Product
	for _, product := range products {
		var responseCompanyID int
		if product.CompanyID.Valid {
			responseCompanyID = int(product.CompanyID.Int32)
		}
		result = append(result, &model.Product{
			ID:              fmt.Sprintf("%d", product.ID),
			Name:            product.Name,
			Description:     product.Description,
			Price:           int(product.Price),
			OwnerID:         int(product.OwnerID),
			CompanyID:       &responseCompanyID,
			ImageLink:       product.ImageLink,
			AvailableStocks: int(product.AvailableStocks),
			IsNegotiable:    product.IsNegotiable,
			Sold:            product.Sold,
			Likes:           int(product.Likes),
			Category:        product.Category,
		})
	}

	return result, nil
}

// GetProduct is the resolver for the getProduct field.
func (r *queryResolver) GetProduct(ctx context.Context, id string) (*model.Product, error) {
	productID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID: %w", err)
	}

	product, err := r.Store.GetProduct(ctx, int32(productID))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("product not found")
		}
		return nil, fmt.Errorf("failed to get product: %w", err)
	}

	var responseCompanyID int
	if product.CompanyID.Valid {
		responseCompanyID = int(product.CompanyID.Int32)
	} else {
		responseCompanyID = 0
	}

	return &model.Product{
		ID:              fmt.Sprintf("%d", product.ID),
		Name:            product.Name,
		Description:     product.Description,
		Price:           int(product.Price),
		OwnerID:         int(product.OwnerID),
		CompanyID:       &responseCompanyID,
		ImageLink:       product.ImageLink,
		AvailableStocks: int(product.AvailableStocks),
		IsNegotiable:    product.IsNegotiable,
		Sold:            product.Sold,
		Likes:           int(product.Likes),
		Category:        product.Category,
	}, nil
}

// GetProductsAdvanced is the resolver for the getProductsAdvanced field.
func (r *queryResolver) GetProductsAdvanced(ctx context.Context, search *string, minPrice *int, maxPrice *int, minStock *int, sold *bool, companyID *int, sortBy *string, limit *int, offset *int) ([]*model.Product, error) {
	products, err := r.ProductService.GetProductsAdvanced(ctx, services.GetProductsAdvancedParams{
		Search:    search,
		MinPrice:  minPrice,
		MaxPrice:  maxPrice,
		MinStock:  minStock,
		Sold:      sold,
		CompanyID: companyID,
		SortBy:    sortBy,
		Limit:     limit,
		Offset:    offset,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get products: %w", err)
	}

	var result []*model.Product
	for _, product := range products {
		var responseCompanyID int
		if product.CompanyID.Valid {
			responseCompanyID = int(product.CompanyID.Int32)
		}
		result = append(result, &model.Product{
			ID:              fmt.Sprintf("%d", product.ID),
			Name:            product.Name,
			Description:     product.Description,
			Price:           int(product.Price),
			OwnerID:         int(product.OwnerID),
			CompanyID:       &responseCompanyID,
			ImageLink:       product.ImageLink,
			AvailableStocks: int(product.AvailableStocks),
			IsNegotiable:    product.IsNegotiable,
			Sold:            product.Sold,
			Likes:           int(product.Likes),
			Category:        product.Category,
		})
	}

	return result, nil
}

// GetProductsByOwner is the resolver for the getProductsByOwner field.
func (r *queryResolver) GetProductsByOwner(ctx context.Context, ownerID string) ([]*model.Product, error) {
	products, err := r.ProductService.GetProductsByOwner(ctx, ownerID)
	if err != nil {
		return nil, err
	}

	var result []*model.Product
	for _, product := range products {
		var responseCompanyID int
		if product.CompanyID.Valid {
			responseCompanyID = int(product.CompanyID.Int32)
		}
		result = append(result, &model.Product{
			ID:              fmt.Sprintf("%d", product.ID),
			Name:            product.Name,
			Description:     product.Description,
			Price:           int(product.Price),
			OwnerID:         int(product.OwnerID),
			CompanyID:       &responseCompanyID,
			ImageLink:       product.ImageLink,
			AvailableStocks: int(product.AvailableStocks),
			IsNegotiable:    product.IsNegotiable,
			Sold:            product.Sold,
			Likes:           int(product.Likes),
			Category:        product.Category,
		})
	}

	return result, nil
}

// GetProductCount is the resolver for the getProductCount field.
func (r *queryResolver) GetProductCount(ctx context.Context, search *string, minPrice *int, maxPrice *int, minStock *int, sold *bool, companyID *int) (int, error) {
	count, err := r.ProductService.GetProductCount(ctx, services.GetProductsAdvancedParams{
		Search:    search,
		MinPrice:  minPrice,
		MaxPrice:  maxPrice,
		MinStock:  minStock,
		Sold:      sold,
		CompanyID: companyID,
	})
	if err != nil {
		return 0, fmt.Errorf("failed to get product count: %w", err)
	}
	return int(count), nil
}

// GetCart is the resolver for the getCart field.
func (r *queryResolver) GetCart(ctx context.Context) (*model.Cart, error) {
	authCtx, err := GetAuthFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required")
	}

	cartItems, err := r.Store.GetCartItems(ctx, int32(authCtx.UserID))
	if err != nil {
		return nil, fmt.Errorf("failed to get cart items: %w", err)
	}

	var items []*model.CartItem
	var totalPrice int

	for _, item := range cartItems {
		product := &model.Product{
			ID:              fmt.Sprintf("%d", item.ProductID),
			Name:            item.Name,
			Price:           int(item.Price),
			ImageLink:       item.ImageLink,
			AvailableStocks: int(item.AvailableStocks),
		}
		items = append(items, &model.CartItem{
			ID:        fmt.Sprintf("%d", item.ID),
			UserID:    int(item.UserID),
			ProductID: int(item.ProductID),
			Quantity:  int(item.Quantity),
			Product:   product,
		})
		totalPrice += int(item.Price) * int(item.Quantity)
	}

	totalItems, err := r.Store.GetCartItemCount(ctx, int32(authCtx.UserID))
	if err != nil {
		return nil, fmt.Errorf("failed to get cart item count: %w", err)
	}

	return &model.Cart{
		Items:      items,
		TotalItems: int(totalItems),
		TotalPrice: totalPrice,
	}, nil
}

// GetCartItemCount is the resolver for the getCartItemCount field.
func (r *queryResolver) GetCartItemCount(ctx context.Context) (int, error) {
	authCtx, err := GetAuthFromContext(ctx)
	if err != nil {
		return 0, fmt.Errorf("authentication required")
	}

	count, err := r.Store.GetCartItemCount(ctx, int32(authCtx.UserID))
	if err != nil {
		return 0, fmt.Errorf("failed to get cart item count: %w", err)
	}

	return int(count), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
