// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToCart = `-- name: AddToCart :one
INSERT INTO cart_items (user_id, product_id, quantity, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (user_id, product_id)
DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity, updated_at = NOW()
RETURNING id, user_id, product_id, quantity, created_at, updated_at
`

type AddToCartParams struct {
	UserID    int32 `db:"user_id" json:"user_id"`
	ProductID int32 `db:"product_id" json:"product_id"`
	Quantity  int32 `db:"quantity" json:"quantity"`
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addToCart, arg.UserID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE user_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, clearCart, userID)
	return err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, user_id, product_id, quantity, created_at, updated_at FROM cart_items
WHERE user_id = $1 AND product_id = $2
LIMIT 1
`

type GetCartItemParams struct {
	UserID    int32 `db:"user_id" json:"user_id"`
	ProductID int32 `db:"product_id" json:"product_id"`
}

func (q *Queries) GetCartItem(ctx context.Context, arg GetCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItem, arg.UserID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemCount = `-- name: GetCartItemCount :one
SELECT COALESCE(SUM(quantity), 0)::int as total_items
FROM cart_items
WHERE user_id = $1
`

func (q *Queries) GetCartItemCount(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getCartItemCount, userID)
	var total_items int32
	err := row.Scan(&total_items)
	return total_items, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT ci.id, ci.user_id, ci.product_id, ci.quantity, ci.created_at, ci.updated_at, p.name, p.price, p.image_link, p.available_stocks
FROM cart_items ci
JOIN products p ON ci.product_id = p.id
WHERE ci.user_id = $1
ORDER BY ci.created_at DESC
`

type GetCartItemsRow struct {
	ID              int32              `db:"id" json:"id"`
	UserID          int32              `db:"user_id" json:"user_id"`
	ProductID       int32              `db:"product_id" json:"product_id"`
	Quantity        int32              `db:"quantity" json:"quantity"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Name            string             `db:"name" json:"name"`
	Price           int32              `db:"price" json:"price"`
	ImageLink       string             `db:"image_link" json:"image_link"`
	AvailableStocks int32              `db:"available_stocks" json:"available_stocks"`
}

func (q *Queries) GetCartItems(ctx context.Context, userID int32) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartItemsRow
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Price,
			&i.ImageLink,
			&i.AvailableStocks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromCart = `-- name: RemoveFromCart :exec
DELETE FROM cart_items
WHERE user_id = $1 AND product_id = $2
`

type RemoveFromCartParams struct {
	UserID    int32 `db:"user_id" json:"user_id"`
	ProductID int32 `db:"product_id" json:"product_id"`
}

func (q *Queries) RemoveFromCart(ctx context.Context, arg RemoveFromCartParams) error {
	_, err := q.db.Exec(ctx, removeFromCart, arg.UserID, arg.ProductID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET quantity = $3, updated_at = NOW()
WHERE user_id = $1 AND product_id = $2
RETURNING id, user_id, product_id, quantity, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	UserID    int32 `db:"user_id" json:"user_id"`
	ProductID int32 `db:"product_id" json:"product_id"`
	Quantity  int32 `db:"quantity" json:"quantity"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.UserID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
