// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (
    user_id,
    token,
    expires_at,
    created_at
) VALUES (
    $1, 
    $2,
    $3, 
    CURRENT_TIMESTAMP
)
RETURNING id, user_id, token, expires_at, verified_at, created_at
`

type CreateEmailVerificationParams struct {
	UserID    int32              `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, createEmailVerification, arg.UserID, arg.Token, arg.ExpiresAt)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredEmailVerifications = `-- name: DeleteExpiredEmailVerifications :exec
DELETE FROM email_verifications
WHERE expires_at < CURRENT_TIMESTAMP AND verified_at IS NULL
`

func (q *Queries) DeleteExpiredEmailVerifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredEmailVerifications)
	return err
}

const getEmailVerificationByToken = `-- name: GetEmailVerificationByToken :one
SELECT id, user_id, token, expires_at, verified_at, created_at FROM email_verifications
WHERE token = $1 AND verified_at IS NULL AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

func (q *Queries) GetEmailVerificationByToken(ctx context.Context, token string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByToken, token)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :one
UPDATE email_verifications
SET verified_at = CURRENT_TIMESTAMP
WHERE token = $1 AND verified_at IS NULL
RETURNING id, user_id, token, expires_at, verified_at, created_at
`

func (q *Queries) MarkEmailVerified(ctx context.Context, token string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, markEmailVerified, token)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserIsVerified = `-- name: UpdateUserIsVerified :one
UPDATE users
SET is_verified = TRUE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, username, hashed_password, full_name, phone_number, address, payment_method, is_verified, is_active, company_id, password_changed_at, created_at, updated_at, last_login_at
`

func (q *Queries) UpdateUserIsVerified(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, updateUserIsVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.PhoneNumber,
		&i.Address,
		&i.PaymentMethod,
		&i.IsVerified,
		&i.IsActive,
		&i.CompanyID,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
