// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Company struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Product struct {
	ID              int32         `json:"id"`
	Name            string        `json:"name"`
	ImageLink       string        `json:"image_link"`
	Description     string        `json:"description"`
	AvailableStocks int32         `json:"available_stocks"`
	Price           int32         `json:"price"`
	IsNegotiable    bool          `json:"is_negotiable"`
	OwnerID         int32         `json:"owner_id"`
	CompanyID       sql.NullInt32 `json:"company_id"`
	Likes           int32         `json:"likes"`
	Sold            bool          `json:"sold"`
}

type ProductLike struct {
	ProductID int32     `json:"product_id"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID               int32         `json:"id"`
	Username         string        `json:"username"`
	HashedPassword   string        `json:"hashed_password"`
	Email            string        `json:"email"`
	FullName         string        `json:"full_name"`
	Address          string        `json:"address"`
	PhoneNumber      string        `json:"phone_number"`
	PaymentMethod    string        `json:"payment_method"`
	PasswordChangeAt time.Time     `json:"password_change_at"`
	CompanyID        sql.NullInt32 `json:"company_id"`
}
