// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID        int32              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EmailVerification struct {
	ID         int32              `db:"id" json:"id"`
	UserID     int32              `db:"user_id" json:"user_id"`
	Token      string             `db:"token" json:"token"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	VerifiedAt pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type LoginHistory struct {
	ID            int32              `db:"id" json:"id"`
	UserID        pgtype.Int4        `db:"user_id" json:"user_id"`
	Email         pgtype.Text        `db:"email" json:"email"`
	LoginStatus   string             `db:"login_status" json:"login_status"`
	IpAddress     *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent     pgtype.Text        `db:"user_agent" json:"user_agent"`
	Location      []byte             `db:"location" json:"location"`
	FailureReason pgtype.Text        `db:"failure_reason" json:"failure_reason"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PasswordReset struct {
	ID        int32              `db:"id" json:"id"`
	UserID    int32              `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	IpAddress *netip.Addr        `db:"ip_address" json:"ip_address"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Product struct {
	ID              int32              `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	ImageLink       string             `db:"image_link" json:"image_link"`
	Description     string             `db:"description" json:"description"`
	AvailableStocks int32              `db:"available_stocks" json:"available_stocks"`
	Price           int32              `db:"price" json:"price"`
	IsNegotiable    bool               `db:"is_negotiable" json:"is_negotiable"`
	OwnerID         int32              `db:"owner_id" json:"owner_id"`
	CompanyID       pgtype.Int4        `db:"company_id" json:"company_id"`
	Likes           int32              `db:"likes" json:"likes"`
	Sold            bool               `db:"sold" json:"sold"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProductLike struct {
	ProductID int32              `db:"product_id" json:"product_id"`
	UserID    int32              `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Role struct {
	ID          int32              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SocialAccount struct {
	ID             int32              `db:"id" json:"id"`
	UserID         int32              `db:"user_id" json:"user_id"`
	Provider       string             `db:"provider" json:"provider"`
	ProviderUserID string             `db:"provider_user_id" json:"provider_user_id"`
	ProviderEmail  pgtype.Text        `db:"provider_email" json:"provider_email"`
	AccessToken    pgtype.Text        `db:"access_token" json:"access_token"`
	RefreshToken   pgtype.Text        `db:"refresh_token" json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `db:"token_expires_at" json:"token_expires_at"`
	ProfileData    []byte             `db:"profile_data" json:"profile_data"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID                int32              `db:"id" json:"id"`
	Email             string             `db:"email" json:"email"`
	Username          string             `db:"username" json:"username"`
	HashedPassword    string             `db:"hashed_password" json:"hashed_password"`
	FullName          string             `db:"full_name" json:"full_name"`
	PhoneNumber       pgtype.Text        `db:"phone_number" json:"phone_number"`
	Address           pgtype.Text        `db:"address" json:"address"`
	PaymentMethod     pgtype.Text        `db:"payment_method" json:"payment_method"`
	IsVerified        pgtype.Bool        `db:"is_verified" json:"is_verified"`
	IsActive          pgtype.Bool        `db:"is_active" json:"is_active"`
	CompanyID         pgtype.Int4        `db:"company_id" json:"company_id"`
	PasswordChangedAt pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastLoginAt       pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
}

type UserRole struct {
	UserID     int32              `db:"user_id" json:"user_id"`
	RoleID     int32              `db:"role_id" json:"role_id"`
	AssignedAt pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
}

type UserSecurity struct {
	UserID              int32              `db:"user_id" json:"user_id"`
	TwoFactorEnabled    pgtype.Bool        `db:"two_factor_enabled" json:"two_factor_enabled"`
	TwoFactorSecret     pgtype.Text        `db:"two_factor_secret" json:"two_factor_secret"`
	BackupCodes         []string           `db:"backup_codes" json:"backup_codes"`
	FailedLoginAttempts pgtype.Int4        `db:"failed_login_attempts" json:"failed_login_attempts"`
	AccountLockedUntil  pgtype.Timestamptz `db:"account_locked_until" json:"account_locked_until"`
	SecurityQuestions   []byte             `db:"security_questions" json:"security_questions"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserSession struct {
	ID             int32              `db:"id" json:"id"`
	UserID         int32              `db:"user_id" json:"user_id"`
	SessionToken   string             `db:"session_token" json:"session_token"`
	RefreshToken   pgtype.Text        `db:"refresh_token" json:"refresh_token"`
	IpAddress      *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent      pgtype.Text        `db:"user_agent" json:"user_agent"`
	DeviceInfo     []byte             `db:"device_info" json:"device_info"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastActivityAt pgtype.Timestamptz `db:"last_activity_at" json:"last_activity_at"`
	IsActive       pgtype.Bool        `db:"is_active" json:"is_active"`
}
