// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_resets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (
    user_id,
    token,
    expires_at,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    CURRENT_TIMESTAMP
)
RETURNING id, user_id, token, expires_at, used_at, ip_address, created_at
`

type CreatePasswordResetParams struct {
	UserID    int32              `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResets = `-- name: DeleteExpiredPasswordResets :exec
DELETE FROM password_resets
WHERE expires_at < CURRENT_TIMESTAMP AND used_at IS NULL
`

func (q *Queries) DeleteExpiredPasswordResets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResets)
	return err
}

const getPasswordResetByToken = `-- name: GetPasswordResetByToken :one
SELECT id, user_id, token, expires_at, used_at, ip_address, created_at FROM password_resets
WHERE token = $1 AND used_at IS NULL AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

func (q *Queries) GetPasswordResetByToken(ctx context.Context, token string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByToken, token)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUserPasswordResets = `-- name: InvalidateUserPasswordResets :exec
UPDATE password_resets
SET used_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidateUserPasswordResets(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, invalidateUserPasswordResets, userID)
	return err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :one
UPDATE password_resets
SET used_at = CURRENT_TIMESTAMP
WHERE token = $1 AND used_at IS NULL
RETURNING id, user_id, token, expires_at, used_at, ip_address, created_at
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, token string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, markPasswordResetUsed, token)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}
