// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, hashed_password, email, full_name, address, phone_number, payment_method, password_change_at, company_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, username, hashed_password, email, full_name, address, phone_number, payment_method, password_change_at, company_id
`

type CreateUserParams struct {
	Username         string        `json:"username"`
	HashedPassword   string        `json:"hashed_password"`
	Email            string        `json:"email"`
	FullName         string        `json:"full_name"`
	Address          string        `json:"address"`
	PhoneNumber      string        `json:"phone_number"`
	PaymentMethod    string        `json:"payment_method"`
	PasswordChangeAt time.Time     `json:"password_change_at"`
	CompanyID        sql.NullInt32 `json:"company_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.Email,
		arg.FullName,
		arg.Address,
		arg.PhoneNumber,
		arg.PaymentMethod,
		arg.PasswordChangeAt,
		arg.CompanyID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.Email,
		&i.FullName,
		&i.Address,
		&i.PhoneNumber,
		&i.PaymentMethod,
		&i.PasswordChangeAt,
		&i.CompanyID,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, hashed_password, email, full_name, address, phone_number, payment_method, password_change_at, company_id FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.Email,
		&i.FullName,
		&i.Address,
		&i.PhoneNumber,
		&i.PaymentMethod,
		&i.PasswordChangeAt,
		&i.CompanyID,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, hashed_password, email, full_name, address, phone_number, payment_method, password_change_at, company_id FROM users
ORDER BY id
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.Email,
			&i.FullName,
			&i.Address,
			&i.PhoneNumber,
			&i.PaymentMethod,
			&i.PasswordChangeAt,
			&i.CompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
