// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, hashed_password, email, full_name, address, phone_number, payment_method, password_changed_at, company_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, email, username, hashed_password, full_name, phone_number, address, payment_method, is_verified, is_active, company_id, password_changed_at, created_at, updated_at, last_login_at
`

type CreateUserParams struct {
	Username          string             `db:"username" json:"username"`
	HashedPassword    string             `db:"hashed_password" json:"hashed_password"`
	Email             string             `db:"email" json:"email"`
	FullName          string             `db:"full_name" json:"full_name"`
	Address           pgtype.Text        `db:"address" json:"address"`
	PhoneNumber       pgtype.Text        `db:"phone_number" json:"phone_number"`
	PaymentMethod     pgtype.Text        `db:"payment_method" json:"payment_method"`
	PasswordChangedAt pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	CompanyID         pgtype.Int4        `db:"company_id" json:"company_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.Email,
		arg.FullName,
		arg.Address,
		arg.PhoneNumber,
		arg.PaymentMethod,
		arg.PasswordChangedAt,
		arg.CompanyID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.PhoneNumber,
		&i.Address,
		&i.PaymentMethod,
		&i.IsVerified,
		&i.IsActive,
		&i.CompanyID,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, username, hashed_password, full_name, phone_number, address, payment_method, is_verified, is_active, company_id, password_changed_at, created_at, updated_at, last_login_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.PhoneNumber,
		&i.Address,
		&i.PaymentMethod,
		&i.IsVerified,
		&i.IsActive,
		&i.CompanyID,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, hashed_password, full_name, phone_number, address, payment_method, is_verified, is_active, company_id, password_changed_at, created_at, updated_at, last_login_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.PhoneNumber,
		&i.Address,
		&i.PaymentMethod,
		&i.IsVerified,
		&i.IsActive,
		&i.CompanyID,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, email, username, hashed_password, full_name, phone_number, address, payment_method, is_verified, is_active, company_id, password_changed_at, created_at, updated_at, last_login_at FROM users
ORDER BY id
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.HashedPassword,
			&i.FullName,
			&i.PhoneNumber,
			&i.Address,
			&i.PaymentMethod,
			&i.IsVerified,
			&i.IsActive,
			&i.CompanyID,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    username = coalesce($1, username),
    hashed_password = coalesce($2, hashed_password),
    email = coalesce($3, email),
    full_name = coalesce($4, full_name),
    address = coalesce($5, address),
    phone_number = coalesce($6, phone_number),
    payment_method = coalesce($7, payment_method),
    password_changed_at = coalesce($8, password_changed_at),
    company_id = coalesce($9, company_id)
WHERE id = $10
RETURNING id, email, username, hashed_password, full_name, phone_number, address, payment_method, is_verified, is_active, company_id, password_changed_at, created_at, updated_at, last_login_at
`

type UpdateUserParams struct {
	Username          pgtype.Text        `db:"username" json:"username"`
	HashedPassword    pgtype.Text        `db:"hashed_password" json:"hashed_password"`
	Email             pgtype.Text        `db:"email" json:"email"`
	FullName          pgtype.Text        `db:"full_name" json:"full_name"`
	Address           pgtype.Text        `db:"address" json:"address"`
	PhoneNumber       pgtype.Text        `db:"phone_number" json:"phone_number"`
	PaymentMethod     pgtype.Text        `db:"payment_method" json:"payment_method"`
	PasswordChangedAt pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	CompanyID         pgtype.Int4        `db:"company_id" json:"company_id"`
	ID                int32              `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.HashedPassword,
		arg.Email,
		arg.FullName,
		arg.Address,
		arg.PhoneNumber,
		arg.PaymentMethod,
		arg.PasswordChangedAt,
		arg.CompanyID,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.PhoneNumber,
		&i.Address,
		&i.PaymentMethod,
		&i.IsVerified,
		&i.IsActive,
		&i.CompanyID,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
