// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_security.sql

package db

import (
	"context"
)

const createUserSecurity = `-- name: CreateUserSecurity :one
INSERT INTO user_security (
    user_id,
    two_factor_enabled,
    failed_login_attempts,
    account_locked_until,
    security_questions,
    created_at,
    updated_at
) VALUES (
    $1, 
    FALSE,
    0, 
    NULL, 
    $2, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
)
RETURNING user_id, two_factor_enabled, two_factor_secret, backup_codes, failed_login_attempts, account_locked_until, security_questions, created_at, updated_at
`

type CreateUserSecurityParams struct {
	UserID            int32  `db:"user_id" json:"user_id"`
	SecurityQuestions []byte `db:"security_questions" json:"security_questions"`
}

func (q *Queries) CreateUserSecurity(ctx context.Context, arg CreateUserSecurityParams) (UserSecurity, error) {
	row := q.db.QueryRow(ctx, createUserSecurity, arg.UserID, arg.SecurityQuestions)
	var i UserSecurity
	err := row.Scan(
		&i.UserID,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.BackupCodes,
		&i.FailedLoginAttempts,
		&i.AccountLockedUntil,
		&i.SecurityQuestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
