// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Mutation struct {
}

type Product struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	ImageLink       string `json:"image_link"`
	Description     string `json:"description"`
	AvailableStocks int    `json:"available_stocks"`
	Price           int    `json:"price"`
	IsNegotiable    bool   `json:"is_negotiable"`
	OwnerID         int    `json:"owner_id"`
	CompanyID       *int   `json:"company_id,omitempty"`
	Likes           int    `json:"likes"`
	Sold            bool   `json:"sold"`
}

type Query struct {
}

type UpdateUserInput struct {
	Username      *string `json:"username,omitempty"`
	Password      *string `json:"password,omitempty"`
	Email         *string `json:"email,omitempty"`
	FullName      *string `json:"full_name,omitempty"`
	Address       *string `json:"address,omitempty"`
	PhoneNumber   *string `json:"phone_number,omitempty"`
	PaymentMethod *string `json:"payment_method,omitempty"`
	CompanyID     *int    `json:"company_id,omitempty"`
}

type User struct {
	ID               string `json:"id"`
	Username         string `json:"username"`
	HashedPassword   string `json:"hashed_password"`
	Email            string `json:"email"`
	FullName         string `json:"full_name"`
	Address          string `json:"address"`
	PhoneNumber      string `json:"phone_number"`
	PaymentMethod    string `json:"payment_method"`
	PasswordChangeAt string `json:"password_change_at"`
	CompanyID        *int   `json:"company_id,omitempty"`
}

type UserInput struct {
	Username      string `json:"username"`
	Password      string `json:"password"`
	Email         string `json:"email"`
	FullName      string `json:"full_name"`
	Address       string `json:"address"`
	PhoneNumber   string `json:"phone_number"`
	PaymentMethod string `json:"payment_method"`
	CompanyID     *int   `json:"company_id,omitempty"`
}
