// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/starjardin/onja-products/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -package mockdb --destination db/mock/store.go github.com/starjardin/onja-products/db/sqlc Store
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}
